- project:
    check:
      queue: "thoth-station/core"
      jobs:
        - "thoth-github-wip"
        - "thoth-apply-openshift-templates":
            vars:
              target_project: "thoth-test-core"
        # - "thoth-coala"
        # - "thoth-pytest"
    gate:
      jobs:
        - "thoth-coala"
        - "thoth-pytest"

    post:
      jobs:
        - "trigger-build":
            vars:
              cluster: "paas.psi.redhat.com"
              namespace: "thoth-test-core"
              buildConfigName: "metrics-exporter"
        - "thoth-apply-openshift-templates":
            vars:
              target_project: "thoth-test-core"

    kebechet-auto-gate:
      jobs:
        - "thoth-coala"
        - "thoth-pytest"
