- project:
    check:
      queue: "thoth-station/core"
      jobs:
        - "thoth-github-wip"
        - "thoth-apply-openshift-templates":
            vars:
              target_project: "thoth-test-core"
        # - "thoth-coala"
        # - "thoth-pytest"
    gate:
      jobs:
        - "thoth-coala"
        - "thoth-pytest"

    post:
      jobs:
        - "trigger-build":
            vars:
              cluster: "paas.psi.redhat.com"
              namespace: "thoth-test-core"
              buildConfigName: "metrics-exporter"
        - "thoth-apply-openshift-templates":
            vars:
              target_project: "thoth-test-core"

    kebechet-auto-gate:
      jobs:
        - "thoth-coala"
        - "thoth-pytest"

- job:
    name: thoth-apply-openshift-templates
    parent: base-openshift-pod
    nodeset:
      nodes:
        - name: pod
          label: thoth-ops
    run: openshift.yaml
    secrets:
      - name: thoth_ops
        secret: thoth_ops

- secret:
    name: thoth_ops
    data:
      key: !encrypted/pkcs1-oaep
        - J09kP/EyxNqXoSLiE4zhYBXoscfDLPXT99fMRLmD4mEfi57G/ax8WXaAGKPu8t7eELVKh
          u1MXnXD5YMJFvZJm/CgPl7r5e6UbGzuvnh5k4MXLwZx5JkvoAy9xmzdoeswwFQ9G4gK+n
          fmDzoEGGlh+99/VY69A9bz2Igh60J1rop3UcgYQuXj9bQ8of4oHinyrW6KdF+d/fr+f5z
          iX5BywPGBRvjsdxJJLMQaZxSokPXmCKSZ92djr6oxEX9S4MzpaEW4FVur7zU5pXQotQFm
          1IGfWEolvoPHqC6pr/ve4yV0pn/5DH0D7cXxgUFj/wV+9UxdXXxTg4FsructKbJb7QeiL
          B/zvvbWSYGgSDx7P8Mb8wkGjI/cL5lrppWed9TLIrDdKablP3mbE4hbSEM70dIG0xrxwY
          CgqkHm1ctVY95s4bECInbJhVC+prxcyos+fy/vhVNRnWjI2DNXk/O0xorP5rDW5T8ZJaq
          NcVvNrUHJETojwgKGrIWZgiMhM+JsjmYURL/x6gsFOIROahttCdM4fBvCAI3g4FZHMK+S
          R0c8qPwXpkUrlImbUPN0H3n//AIcd8dkhULh47Kam85Qil5kHTnww4ihlXXwVGbaGTO62
          dZsuaPcIjEGCHCh4Go10mmpJEg15ecQoqjixK9dbjCUu/9wpXH0R/bBsPajUF8=
        - kBtXmIZT+TKsihUEqPRKEeO4bNFL1CAvuYh9UpC95rdt2MMUorU2+S/ps7tS4iz4s/MSH
          mjY/VaNkciFhVCuguMK5wPJCAD5EKJ/BuAFeHAk22oY+4FOnSN8mc8kUuXom+arEjwWCb
          eE3q7ibokcn2YZkiXnEVpKKskNGTxpzNl7V33cwrJ91W+9QrNqr8xFP57T4YzOcYY9ePG
          Y6770tJilScwZFVdc+LM7mIdEDHQbT87pNS2AlLoyB5icJlBAWrtxa3chD/tOuP+GgdBi
          SlIHSkAcB8MQDtP9yrCtbwp7urkKXhgTFt06gz7Vuk/p2rA/GdS0HXZu2GgNNFBNOJSqh
          KpmRcsnR6yVTdpAraCpDaV1Ql30b9vtceEhTBOldFkb3s6JUQ8Qov5pFy3ZWw9OGV9bPp
          /6uzKyMVhGTE1gdYfUKwJYOBfjEcf8wneuuo2NCMF+yzDad1wFx3xkVS9nzrTKoumyJu/
          FO6rkVBu0AqyiXoQ4WRAdMSVeeSAmheybE9pDxyQkVy3te+PLFawEBtEw/Ice1A1WuWmr
          jQSyBgLxRLuvtDB6pv2FIxD568T0vZUkC6/M1+fd2z5SLB000wPtwavXjLc8sKo8TL7Lj
          7oER45RcRxiq0tpowTNJxkLXNYSBbZ+GxM+w5uQ+q6fdZXoxXiNpOGnhaOmf+M=
