---
- hosts: all

  vars:
    cluster: "paas.psi.redhat.com"

  tasks:
    - name: "log in as thoth-ops"
      command: "oc login --token $THOTH_OPS_TOKEN"

    - name: "OpenShift whoami"
      command: "oc whoami"
